jwt:
  key: ${key}
  access-token-expiration: 60000
  refresh-token-expiration: 86400000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/application_user
    username: root
    password: root
    driver-class: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    generate-ddl: true

